version: "3"
services:
  unifi-event-monitor:
    container_name: unifi-event-monitor
    image: tborychowski/unifi-event-monitor
    restart: unless-stopped
	environment:
      - HOST=https://<controller IP>:8443
      - USERNAME=<controller username>
	  - PASSWORD=<controller password>
    volumes:
      - type: bind
        source: ./.apprise
        target: /unifi-event-monitor/.apprise
